apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2EKWm5FFKdrVU1FxASfz73hgtdtTIExd,iv:+gO74ZlRpMHYG2H+OC4tJTaUjG7atzilwNxIlRLxllA=,tag:0chsStY9j75v9WdY3S8kmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cndyqzwsajzxrhkj2l04hrnde90gj26klkl85emck3zc28fzlfys8cta9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc0g4K2ZTN0h0bGg5d01O
            S2VzWkxPekNCWEJ2VXZnb095ZUtnVDhTeWxnCkFFcDJoUHVFQ1dUMWRqUmRvUkZh
            TmkvRU9GVjdnZXVNdTRGeFdQU1JpSGMKLS0tIDdMOEprNCt3VS9rSU0rYnZ0U00v
            YXJsL0V3dDBsTTlmK01oUWdpZzBjU00KEZzbNd0Nb+SlvoLT4sZE3ucGRa8KPAhs
            VnZ1LFRKoR/1m7Y8vONWc/CoxAGYjOM4H5ShMyxkC1rnlvDOgV1FtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T04:18:09Z"
    mac: ENC[AES256_GCM,data:2bfDcmXdhrS/S7GjAw6hx7B/xcRCt8BAbL27T8tMb09+gGUFwjwz63jEcKlfEzkCw3PXDhz62ndE/7n9xv2DXDOp/rsdgP/w/cnUmMkGYeXvkq1340MJVzyBUjNBknh5lAcCTxt28Oyt5PU622TWxu2QvfBDaBdpw9S7Qrr9ZYI=,iv:B1w4y2kv2iyV047a1iCn/u04T70DH8pYLeW6NzYbY+0=,tag:sH24cN6tawbSxdcGgFrItQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
