apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:iCK3vcaHlccMoQpqapwq9l8Azqsra5GNOYBSR2O+yLBmCniEamz/4w==,iv:qHwXmKLG+/L1t1e2KB/mwE86HZmCrxKUhs9W9Nek25w=,tag:w5AR20cT4vjSwkzUlOWOgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cndyqzwsajzxrhkj2l04hrnde90gj26klkl85emck3zc28fzlfys8cta9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFI4S25JM1RKdWxaTHdS
            bUxHMWpIU0lSK3lTSzNCQTU4NUdkK2V2cUY4ClVnNkdxVi8rVjVKU0xCK2p1SmpC
            dWd4U1F4YlluNXo3KzRyUmdCTldySGsKLS0tIHR6MkxCUVJMMlNZRWZFeTdOT1lF
            NWxuM3kzUWtucTA5Q3lPMWZsYTVwdHMKIQyFnJ/u877wy3JCVt6QrxxijrqfB6Lo
            jVx79ASe0dj59MLIbYQRyk/Zv5xZiaLN1ZfPxQ6oS63YlWM1MeSNZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T04:18:09Z"
    mac: ENC[AES256_GCM,data:26G2asK/yTSis8dFBFCimubqLcNgNzcjOI5ikV3WUM06rxkTrDSFeVZ7YPvSlLtJQUPJVEA6+QnWzf/BcTybH6GVHgQndMREZiAjYvv7WT6VphQNq4tp2uEgc81Q+Q0tZnuavbQXdlSWAF6MSlR9Nai8/fuRCLbkXExlQb8Wu9A=,iv:FOc2mm509xwtI4sAvLD4h4Jk46CpG7tROfz675XBoFI=,tag:HIKfslZEMcawsO+KSTTqfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
