apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:DOP5CgJa86dQVqFAT6ARmDs6,iv:rOPKsuJfaElVSxuz1p/H7ZNRBzXZt4804lXJ98KMb2w=,tag:1MPcuV7Rag/Stscip6wLUg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:I48Z2GJtxggb4IFocjvtX+dzAsSaaYe4Uelmfi/6yARCtXum,iv:TVfJ/PW4XIJr/Ltk7gqJH4SgAJrx6hcpyJB1aB7fbPE=,tag:dACM8RoOivzdNteAtcg7/Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:mLyLE31/0yCKu4TlqLE7,iv:45H7xbO3XAcL9cCpS9NpXtFX2edTQeZH9V0TAnifVZk=,tag:FVytAqyQt+Lup3wE9bF3ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cndyqzwsajzxrhkj2l04hrnde90gj26klkl85emck3zc28fzlfys8cta9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK09ZV3FEbHF1Nk9YWEV1
            S1hnOE43M0FtNXp0WUM2Z2tUcy9ReXh0YmdZCjVsN2FwTFJEUVAvVXV2eVdzS0pw
            dnhXbXpSRlo0OWNFSzRCdTlWZGVaekUKLS0tIG11OEFjc20yblZnSVR2Nks3Q0hS
            NGkvdVc4bVhUUStVRW05V2kwVldYQVEKkuHWsngICCmwkUPeMUW3/BgoXbKX8eDM
            ntjHp9pONN2kwcjZZd0l21dtEwoqQXqew2mf9ASUZUftxlhCPHFuGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T04:18:09Z"
    mac: ENC[AES256_GCM,data:opuww5aMTdDhYdNuYtz0EzBx50XHthok8z4M87oKECGG9F0l14oS7l1eqqFI0hRLyx+1Ttsww0XnwMWozv1EgsS9KH/zDUHJIBvvUGO2+lqRWFfuLEKGh3uIki5nDTZN0t2tBq5MJTwT4bi0Qv4AkuIx4SSzY3QvqJUu516dJcM=,iv:J7/CeUS+vsAxnAVrQ0inhtRA6GlnGB95DU3r3CLwDvo=,tag:ogy7fyCoKzeYFSMTPhJN5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
